language: node_js
node_js:
  - "10"
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master
  local-dir: build
  on:
    branch: dev